name: PR to Discord
on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main
      - dev
jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Discord
        uses: stegzilla/discord-notify@v4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "New Pull Request: ${{ github.event.pull_request.title }}"
          message: |
            **Repository:** ${{ github.repository }}
            **Branch:** ```${{ github.head_ref }}``` --> ```${{github.base_ref}}```
            **Author:** ${{ github.actor }}
            [View Pull Request](${{ github.event.pull_request.html_url }})
          color: '#3371FF'
          username: ${{ github.event.pull_request.user.login }}
          avatar_url: ${{ github.event.pull_request.user.avatar_url }}
          
